local M = {}

function M.groups(c)
  return {
    Normal = { fg = c.fg, bg = c.bg },
    NormalNC = { fg = c.fg, bg = c.bg },
    NormalFloat = { fg = c.fg, bg = c.bg_light },
    FloatBorder = { fg = c.fg_dim, bg = c.bg_light },
    FloatTitle = { fg = c.blue, bg = c.bg_light, bold = true },

    Cursor = { fg = c.bg, bg = c.fg },
    lCursor = { fg = c.bg, bg = c.fg },
    CursorIM = { fg = c.bg, bg = c.fg },
    TermCursor = { fg = c.bg, bg = c.fg },
    CursorLine = { bg = c.bg_dim },
    CursorColumn = { bg = c.bg_dim },
    ColorColumn = { bg = c.bg_dark },

    LineNr = { fg = c.fg_muted },
    CursorLineNr = { fg = c.orange, bold = true },
    SignColumn = { fg = c.fg_muted, bg = c.bg },
    FoldColumn = { fg = c.fg_muted, bg = c.bg },
    Folded = { fg = c.fg_dim, bg = c.bg_dark },

    Visual = { bg = c.bg_visual },
    VisualNOS = { bg = c.bg_visual },
    Search = { fg = c.fg, bg = c.bg_search },
    IncSearch = { fg = c.bg, bg = c.orange },
    CurSearch = { fg = c.bg, bg = c.orange },
    MatchParen = { fg = c.magenta, bold = true, underline = true },

    StatusLine = { fg = c.fg, bg = c.bg_dark },
    StatusLineNC = { fg = c.fg_subtle, bg = c.bg_dim },
    TabLine = { fg = c.fg_dim, bg = c.bg_dark },
    TabLineFill = { bg = c.bg_dim },
    TabLineSel = { fg = c.fg, bg = c.bg, bold = true },
    WinBar = { fg = c.fg, bg = c.bg },
    WinBarNC = { fg = c.fg_subtle, bg = c.bg },
    WinSeparator = { fg = c.fg_muted },
    VertSplit = { fg = c.fg_muted },

    Pmenu = { fg = c.fg, bg = c.bg_light },
    PmenuSel = { fg = c.fg, bg = c.bg_visual },
    PmenuSbar = { bg = c.bg_dim },
    PmenuThumb = { bg = c.fg_muted },
    PmenuKind = { fg = c.blue, bg = c.bg_light },
    PmenuExtra = { fg = c.fg_dim, bg = c.bg_light },
    WildMenu = { fg = c.fg, bg = c.bg_visual },

    Title = { fg = c.blue, bold = true },
    Directory = { fg = c.blue, bold = true },
    Question = { fg = c.blue },
    MoreMsg = { fg = c.green },
    ModeMsg = { fg = c.fg, bold = true },
    ErrorMsg = { fg = c.red, bold = true },
    WarningMsg = { fg = c.yellow, bold = true },
    NonText = { fg = c.fg_muted },
    SpecialKey = { fg = c.cyan },
    Whitespace = { fg = c.fg_muted },
    Conceal = { fg = c.fg_subtle },
    EndOfBuffer = { fg = c.bg },

    DiffAdd = { bg = c.soft_green },
    DiffChange = { bg = c.soft_yellow },
    DiffDelete = { fg = c.red, bg = c.soft_red },
    DiffText = { bg = c.soft_blue, bold = true },
    DiffAdded = { fg = c.green },
    DiffRemoved = { fg = c.red },
    DiffChanged = { fg = c.yellow },
    DiffFile = { fg = c.blue },
    DiffIndexLine = { fg = c.magenta },
    DiffLine = { fg = c.cyan },

    SpellBad = { sp = c.red, undercurl = true },
    SpellCap = { sp = c.blue, undercurl = true },
    SpellLocal = { sp = c.cyan, undercurl = true },
    SpellRare = { sp = c.magenta, undercurl = true },

    Comment = { fg = c.fg_dim, italic = true },
    Constant = { fg = c.cyan },
    String = { fg = c.green },
    Character = { fg = c.green },
    Number = { fg = c.orange },
    Boolean = { fg = c.orange },
    Float = { fg = c.orange },
    Identifier = { fg = c.fg },
    Function = { fg = c.blue },
    Statement = { fg = c.magenta },
    Conditional = { fg = c.magenta },
    Repeat = { fg = c.magenta },
    Label = { fg = c.yellow },
    Operator = { fg = c.fg_dim },
    Keyword = { fg = c.magenta },
    Exception = { fg = c.red },
    PreProc = { fg = c.yellow },
    Include = { fg = c.magenta },
    Define = { fg = c.magenta },
    Macro = { fg = c.magenta },
    PreCondit = { fg = c.yellow },
    Type = { fg = c.yellow },
    StorageClass = { fg = c.yellow },
    Structure = { fg = c.yellow },
    Typedef = { fg = c.yellow },
    Special = { fg = c.cyan },
    SpecialChar = { fg = c.orange },
    Tag = { fg = c.red },
    Delimiter = { fg = c.fg_dim },
    SpecialComment = { fg = c.fg_subtle, italic = true },
    Debug = { fg = c.orange },
    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Todo = { fg = c.bg, bg = c.yellow, bold = true },
    Error = { fg = c.red },
    Ignore = { fg = c.fg_muted },

    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { fg = c.fg_subtle, italic = true },
    ["@comment.error"] = { fg = c.red, italic = true },
    ["@comment.warning"] = { fg = c.yellow, italic = true },
    ["@comment.todo"] = { fg = c.blue, italic = true, bold = true },
    ["@comment.note"] = { fg = c.cyan, italic = true },

    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = c.orange },
    ["@constant.macro"] = { fg = c.magenta },
    ["@string"] = { link = "String" },
    ["@string.documentation"] = { fg = c.green, italic = true },
    ["@string.regexp"] = { fg = c.cyan },
    ["@string.escape"] = { fg = c.orange },
    ["@string.special"] = { fg = c.cyan },
    ["@string.special.symbol"] = { fg = c.cyan },
    ["@string.special.url"] = { fg = c.blue, underline = true },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@boolean"] = { link = "Boolean" },

    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = c.blue, italic = true },
    ["@function.call"] = { fg = c.blue },
    ["@function.macro"] = { fg = c.magenta },
    ["@function.method"] = { fg = c.blue },
    ["@function.method.call"] = { fg = c.blue },
    ["@constructor"] = { fg = c.yellow },
    ["@parameter"] = { fg = c.fg },
    ["@parameter.builtin"] = { fg = c.orange, italic = true },

    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { fg = c.magenta },
    ["@keyword.operator"] = { fg = c.magenta },
    ["@keyword.import"] = { fg = c.magenta },
    ["@keyword.type"] = { fg = c.magenta },
    ["@keyword.modifier"] = { fg = c.magenta },
    ["@keyword.repeat"] = { fg = c.magenta },
    ["@keyword.return"] = { fg = c.magenta },
    ["@keyword.debug"] = { fg = c.orange },
    ["@keyword.exception"] = { fg = c.red },
    ["@keyword.conditional"] = { fg = c.magenta },
    ["@keyword.conditional.ternary"] = { fg = c.magenta },
    ["@keyword.directive"] = { fg = c.yellow },
    ["@keyword.directive.define"] = { fg = c.yellow },

    ["@operator"] = { link = "Operator" },
    ["@punctuation"] = { fg = c.fg_dim },
    ["@punctuation.delimiter"] = { fg = c.fg_dim },
    ["@punctuation.bracket"] = { fg = c.fg_dim },
    ["@punctuation.special"] = { fg = c.cyan },

    ["@variable"] = { fg = c.fg },
    ["@variable.builtin"] = { fg = c.orange, italic = true },
    ["@variable.parameter"] = { fg = c.fg },
    ["@variable.parameter.builtin"] = { fg = c.orange, italic = true },
    ["@variable.member"] = { fg = c.fg },

    ["@property"] = { fg = c.fg },
    ["@field"] = { fg = c.fg },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.yellow, italic = true },
    ["@type.definition"] = { fg = c.yellow },
    ["@type.qualifier"] = { fg = c.magenta },
    ["@module"] = { fg = c.fg },
    ["@module.builtin"] = { fg = c.orange, italic = true },
    ["@label"] = { link = "Label" },
    ["@attribute"] = { fg = c.yellow },
    ["@attribute.builtin"] = { fg = c.yellow, italic = true },
    ["@namespace"] = { fg = c.fg },

    ["@tag"] = { fg = c.red },
    ["@tag.attribute"] = { fg = c.yellow },
    ["@tag.delimiter"] = { fg = c.fg_dim },

    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.heading"] = { fg = c.blue, bold = true },
    ["@markup.heading.1"] = { fg = c.blue, bold = true },
    ["@markup.heading.2"] = { fg = c.magenta, bold = true },
    ["@markup.heading.3"] = { fg = c.cyan, bold = true },
    ["@markup.heading.4"] = { fg = c.green, bold = true },
    ["@markup.heading.5"] = { fg = c.yellow, bold = true },
    ["@markup.heading.6"] = { fg = c.orange, bold = true },
    ["@markup.quote"] = { fg = c.fg_dim, italic = true },
    ["@markup.math"] = { fg = c.cyan },
    ["@markup.link"] = { fg = c.blue, underline = true },
    ["@markup.link.label"] = { fg = c.cyan },
    ["@markup.link.url"] = { fg = c.blue, underline = true },
    ["@markup.raw"] = { fg = c.green },
    ["@markup.raw.block"] = { fg = c.green },
    ["@markup.list"] = { fg = c.magenta },
    ["@markup.list.checked"] = { fg = c.green },
    ["@markup.list.unchecked"] = { fg = c.fg_dim },

    ["@diff.plus"] = { fg = c.green },
    ["@diff.minus"] = { fg = c.red },
    ["@diff.delta"] = { fg = c.yellow },

    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.decorator"] = { link = "@attribute" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { link = "@type" },
    ["@lsp.type.macro"] = { link = "@function.macro" },
    ["@lsp.type.method"] = { link = "@function.method" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"] = { link = "@variable" },
    ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
    ["@lsp.typemod.variable.injected"] = { link = "@variable" },

    DiagnosticError = { fg = c.red },
    DiagnosticWarn = { fg = c.yellow },
    DiagnosticInfo = { fg = c.blue },
    DiagnosticHint = { fg = c.cyan },
    DiagnosticOk = { fg = c.green },
    DiagnosticUnderlineError = { sp = c.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.blue, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.cyan, undercurl = true },
    DiagnosticUnderlineOk = { sp = c.green, undercurl = true },
    DiagnosticVirtualTextError = { fg = c.red, bg = c.soft_red },
    DiagnosticVirtualTextWarn = { fg = c.yellow, bg = c.soft_yellow },
    DiagnosticVirtualTextInfo = { fg = c.blue, bg = c.soft_blue },
    DiagnosticVirtualTextHint = { fg = c.cyan, bg = c.soft_cyan },
    DiagnosticVirtualTextOk = { fg = c.green, bg = c.soft_green },
    DiagnosticFloatingError = { fg = c.red },
    DiagnosticFloatingWarn = { fg = c.yellow },
    DiagnosticFloatingInfo = { fg = c.blue },
    DiagnosticFloatingHint = { fg = c.cyan },
    DiagnosticFloatingOk = { fg = c.green },
    DiagnosticSignError = { fg = c.red },
    DiagnosticSignWarn = { fg = c.yellow },
    DiagnosticSignInfo = { fg = c.blue },
    DiagnosticSignHint = { fg = c.cyan },
    DiagnosticSignOk = { fg = c.green },
    LspReferenceText = { bg = c.bg_dark },
    LspReferenceRead = { bg = c.bg_dark },
    LspReferenceWrite = { bg = c.bg_dark },
    LspSignatureActiveParameter = { fg = c.orange, bold = true },
    LspCodeLens = { fg = c.fg_subtle, italic = true },
    LspCodeLensSeparator = { fg = c.fg_muted },
    LspInlayHint = { fg = c.fg_subtle, bg = c.bg_dim },

    GitSignsAdd = { fg = c.green },
    GitSignsChange = { fg = c.yellow },
    GitSignsDelete = { fg = c.red },
    GitSignsAddNr = { fg = c.green },
    GitSignsChangeNr = { fg = c.yellow },
    GitSignsDeleteNr = { fg = c.red },
    GitSignsAddLn = { bg = c.soft_green },
    GitSignsChangeLn = { bg = c.soft_yellow },
    GitSignsDeleteLn = { bg = c.soft_red },
    GitSignsCurrentLineBlame = { fg = c.fg_muted, italic = true },

    TelescopeNormal = { fg = c.fg, bg = c.bg_light },
    TelescopeBorder = { fg = c.fg_muted, bg = c.bg_light },
    TelescopePromptNormal = { fg = c.fg, bg = c.bg_dim },
    TelescopePromptBorder = { fg = c.fg_muted, bg = c.bg_dim },
    TelescopePromptTitle = { fg = c.bg, bg = c.blue, bold = true },
    TelescopePromptPrefix = { fg = c.blue },
    TelescopePreviewTitle = { fg = c.bg, bg = c.green, bold = true },
    TelescopeResultsTitle = { fg = c.bg, bg = c.magenta, bold = true },
    TelescopeSelection = { fg = c.fg, bg = c.bg_visual },
    TelescopeSelectionCaret = { fg = c.blue },
    TelescopeMatching = { fg = c.orange, bold = true },
    TelescopeMultiSelection = { fg = c.magenta },

    NeoTreeNormal = { fg = c.fg, bg = c.bg },
    NeoTreeNormalNC = { fg = c.fg, bg = c.bg },
    NeoTreeDirectoryName = { fg = c.blue },
    NeoTreeDirectoryIcon = { fg = c.blue },
    NeoTreeRootName = { fg = c.magenta, bold = true },
    NeoTreeFileName = { fg = c.fg },
    NeoTreeFileIcon = { fg = c.fg_dim },
    NeoTreeIndentMarker = { fg = c.fg_muted },
    NeoTreeGitAdded = { fg = c.green },
    NeoTreeGitConflict = { fg = c.red },
    NeoTreeGitDeleted = { fg = c.red },
    NeoTreeGitModified = { fg = c.yellow },
    NeoTreeGitUntracked = { fg = c.cyan },
    NeoTreeFloatBorder = { fg = c.fg_muted },
    NeoTreeTitleBar = { fg = c.bg, bg = c.blue },

    NvimTreeNormal = { fg = c.fg, bg = c.bg },
    NvimTreeFolderName = { fg = c.blue },
    NvimTreeOpenedFolderName = { fg = c.blue, bold = true },
    NvimTreeEmptyFolderName = { fg = c.fg_subtle },
    NvimTreeRootFolder = { fg = c.magenta, bold = true },
    NvimTreeFolderIcon = { fg = c.blue },
    NvimTreeIndentMarker = { fg = c.fg_muted },
    NvimTreeGitDirty = { fg = c.yellow },
    NvimTreeGitNew = { fg = c.green },
    NvimTreeGitDeleted = { fg = c.red },
    NvimTreeSpecialFile = { fg = c.yellow, underline = true },
    NvimTreeImageFile = { fg = c.magenta },
    NvimTreeExecFile = { fg = c.green, bold = true },

    WhichKey = { fg = c.blue },
    WhichKeyGroup = { fg = c.magenta },
    WhichKeyDesc = { fg = c.fg },
    WhichKeySeparator = { fg = c.fg_muted },
    WhichKeyFloat = { bg = c.bg_light },
    WhichKeyBorder = { fg = c.fg_muted },
    WhichKeyValue = { fg = c.fg_dim },

    IndentBlanklineChar = { fg = c.bg_dark },
    IndentBlanklineContextChar = { fg = c.fg_muted },
    IblIndent = { fg = c.bg_dark },
    IblScope = { fg = c.fg_muted },

    LazyNormal = { fg = c.fg, bg = c.bg_light },
    LazyButton = { bg = c.bg_dim },
    LazyButtonActive = { bg = c.bg_visual, bold = true },
    LazyH1 = { fg = c.bg, bg = c.blue, bold = true },
    LazyProgressDone = { fg = c.green },
    LazyProgressTodo = { fg = c.fg_muted },
    LazyReasonPlugin = { fg = c.magenta },
    LazyReasonStart = { fg = c.green },
    LazyReasonEvent = { fg = c.yellow },
    LazyReasonKeys = { fg = c.cyan },
    LazyReasonCmd = { fg = c.blue },
    LazyReasonRuntime = { fg = c.orange },
    LazyReasonSource = { fg = c.cyan },
    LazyReasonFt = { fg = c.green },

    MasonNormal = { fg = c.fg, bg = c.bg_light },
    MasonHeader = { fg = c.bg, bg = c.blue, bold = true },
    MasonHighlight = { fg = c.blue },
    MasonHighlightBlock = { fg = c.bg, bg = c.blue },
    MasonHighlightBlockBold = { fg = c.bg, bg = c.blue, bold = true },
    MasonMuted = { fg = c.fg_subtle },
    MasonMutedBlock = { fg = c.fg_subtle, bg = c.bg_dim },

    NotifyERRORBorder = { fg = c.red },
    NotifyWARNBorder = { fg = c.yellow },
    NotifyINFOBorder = { fg = c.blue },
    NotifyDEBUGBorder = { fg = c.fg_muted },
    NotifyTRACEBorder = { fg = c.magenta },
    NotifyERRORIcon = { fg = c.red },
    NotifyWARNIcon = { fg = c.yellow },
    NotifyINFOIcon = { fg = c.blue },
    NotifyDEBUGIcon = { fg = c.fg_muted },
    NotifyTRACEIcon = { fg = c.magenta },
    NotifyERRORTitle = { fg = c.red },
    NotifyWARNTitle = { fg = c.yellow },
    NotifyINFOTitle = { fg = c.blue },
    NotifyDEBUGTitle = { fg = c.fg_muted },
    NotifyTRACETitle = { fg = c.magenta },

    DashboardHeader = { fg = c.blue },
    DashboardCenter = { fg = c.fg },
    DashboardFooter = { fg = c.fg_dim, italic = true },
    DashboardKey = { fg = c.orange },
    DashboardDesc = { fg = c.fg_dim },
    DashboardIcon = { fg = c.blue },

    CmpItemAbbr = { fg = c.fg },
    CmpItemAbbrDeprecated = { fg = c.fg_muted, strikethrough = true },
    CmpItemAbbrMatch = { fg = c.blue, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.blue, bold = true },
    CmpItemKind = { fg = c.magenta },
    CmpItemMenu = { fg = c.fg_subtle },
    CmpItemKindText = { fg = c.fg },
    CmpItemKindMethod = { fg = c.blue },
    CmpItemKindFunction = { fg = c.blue },
    CmpItemKindConstructor = { fg = c.yellow },
    CmpItemKindField = { fg = c.cyan },
    CmpItemKindVariable = { fg = c.fg },
    CmpItemKindClass = { fg = c.yellow },
    CmpItemKindInterface = { fg = c.yellow },
    CmpItemKindModule = { fg = c.magenta },
    CmpItemKindProperty = { fg = c.cyan },
    CmpItemKindUnit = { fg = c.orange },
    CmpItemKindValue = { fg = c.orange },
    CmpItemKindEnum = { fg = c.yellow },
    CmpItemKindKeyword = { fg = c.magenta },
    CmpItemKindSnippet = { fg = c.green },
    CmpItemKindColor = { fg = c.cyan },
    CmpItemKindFile = { fg = c.blue },
    CmpItemKindReference = { fg = c.fg_dim },
    CmpItemKindFolder = { fg = c.blue },
    CmpItemKindEnumMember = { fg = c.cyan },
    CmpItemKindConstant = { fg = c.orange },
    CmpItemKindStruct = { fg = c.yellow },
    CmpItemKindEvent = { fg = c.orange },
    CmpItemKindOperator = { fg = c.fg_dim },
    CmpItemKindTypeParameter = { fg = c.yellow },

    FlashMatch = { fg = c.fg, bg = c.bg_search },
    FlashCurrent = { fg = c.bg, bg = c.orange },
    FlashLabel = { fg = c.bg, bg = c.magenta, bold = true },
    FlashBackdrop = { fg = c.fg_muted },

    MiniStatuslineModeNormal = { fg = c.bg, bg = c.blue, bold = true },
    MiniStatuslineModeInsert = { fg = c.bg, bg = c.green, bold = true },
    MiniStatuslineModeVisual = { fg = c.bg, bg = c.magenta, bold = true },
    MiniStatuslineModeReplace = { fg = c.bg, bg = c.red, bold = true },
    MiniStatuslineModeCommand = { fg = c.bg, bg = c.yellow, bold = true },
    MiniIndentscopeSymbol = { fg = c.fg_muted },
    MiniCursorword = { underline = true },
    MiniCursorwordCurrent = { underline = true },

    BufferLineFill = { bg = c.bg_dim },
    BufferLineBackground = { fg = c.fg_subtle, bg = c.bg_dark },
    BufferLineBufferSelected = { fg = c.fg, bg = c.bg, bold = true },
    BufferLineBufferVisible = { fg = c.fg_dim, bg = c.bg_dim },
    BufferLineIndicatorSelected = { fg = c.blue },
    BufferLineModified = { fg = c.yellow, bg = c.bg_dark },
    BufferLineModifiedSelected = { fg = c.yellow, bg = c.bg },
    BufferLineSeparator = { fg = c.bg_dim, bg = c.bg_dark },
    BufferLineSeparatorSelected = { fg = c.bg_dim, bg = c.bg },

    TroubleNormal = { fg = c.fg, bg = c.bg },
    TroubleText = { fg = c.fg },
    TroubleCount = { fg = c.magenta, bg = c.bg_dark },
    TroubleSource = { fg = c.fg_subtle },

    RainbowDelimiterRed = { fg = c.red },
    RainbowDelimiterYellow = { fg = c.yellow },
    RainbowDelimiterBlue = { fg = c.blue },
    RainbowDelimiterOrange = { fg = c.orange },
    RainbowDelimiterGreen = { fg = c.green },
    RainbowDelimiterViolet = { fg = c.magenta },
    RainbowDelimiterCyan = { fg = c.cyan },

    RenderMarkdownH1 = { fg = c.blue, bold = true },
    RenderMarkdownH2 = { fg = c.magenta, bold = true },
    RenderMarkdownH3 = { fg = c.cyan, bold = true },
    RenderMarkdownCode = { bg = c.bg_dim },
    RenderMarkdownCodeInline = { fg = c.green, bg = c.bg_dim },
    RenderMarkdownBullet = { fg = c.magenta },
    RenderMarkdownQuote = { fg = c.fg_dim },
    RenderMarkdownLink = { fg = c.blue },

    healthSuccess = { fg = c.green },
    healthWarning = { fg = c.yellow },
    healthError = { fg = c.red },
  }
end

return M
